### PR TITLE
Add no2 diff layer

### PR DESCRIPTION
**Pull request by jvntf**
#322 WIP

@drewbo a few things needed to complete this:
color map?
comparison?
info text?
domain?

### CODE REVIEW

**Comment by drewbo** [comment]
@jvntf 
- color map? let's use same as CO2 diff, unsure on scale
- comparison? none
- info text? @barrylefer can you provide info text for this product as well (~1 sentence)
- domain? dates to match the same as the first NO2 product

**Comment by barrylefer** [comment]
Drew.  Wow.  Gald to see on the progress! Thanks again for making all the changes.  I am camping Friday-Sunday.  But happy to look at this on Monday.  Take care and have a nice weekend.

**Comment by olafveerman** [comment]
All done, except for the scale. Asked Zach for input.

**Comment by barrylefer** [comment]
Great thanks!!

**Pull request merged**
