### PR TITLE
Comparison for stories

### PR DESCRIPTION
**Pull request by danielfdsilva**
This PR implements the ability to enable comparison for layer stories.

> :warning::warning: Adding comparison to stories was not straightforward and several pieces of code were touched. Al the other map related pages should be tested to ensure that everything still works. :warning::warning:

Adding the compare functionality to a story layer is done through the `compare` property inside `visual`.
This can be done in a couple of different ways depending of some factors:

### Enabling the existing compare on an existing layer

If a given layer already has the compare defined (because is used on other pages) it is possible to simply enable it and maintain all settings.
```
  visual: {
    type: 'map-layer',
    data: {
      layers: ['no2'],
      date: '2020-03-01T00:00:00Z',
      compare: true
    }
  }
```

### Extending the existing compare on an existing layer

If the existent compare properties do not suit the story's visuals, they can be overridden. The layer's base compare is used and properties provided through the story are used as overrides.
```
visual: {
  type: 'map-layer',
  data: {
    layers: ['no2'],
    date: '2020-03-01T00:00:00Z',
    compare: {
      mapLabel: date => '2020-01-01 vs 2020-03-01',
      compareDate: date => new Date('2020-01-01T00:00:00Z')
    }
  }
}
```

In the above example we're changing the compare date to a fixed one (no2 default is 2y from the selected date). We're also changing the map compare label.

### Adding a compare to a layer

If the layer being displayed doesn't have a compare defined in the app it is possible to add one, using the `compare` to provide all the properties.
```
visual: {
  type: 'map-layer',
  data: {
    spotlight: null,
    date: null,
    bbox: [-30, 30, 30, -30],
    layers: [
      {
        id: 'population-neo',
        name: 'Population',
        type: 'raster-timeseries',
        source: {
          type: 'raster',
          tiles: [
            'url'
          ]
        }
      }
    ],
    compare: {
      mapLabel: date => 'Foo vs Bar',
      compareDate: date => new Date('2020-01-01T00:00:00Z')
      source: {
        type: 'raster-timeseries',
        tiles: [
          'url compare'
        ]
      }
    }
  }
}
```

Functions:
 - `mapLabel(date: Date)` - Must return a string to displayed.
 - `compareDate(date: Date)` - Must return a date object to use as comparison.

### CODE REVIEW

**Comment by danielfdsilva** [comment]
Added the comparison for `raster` layer types.

Comparison works the same way as for `raster-timeseries`but since there are no `raster` layers in the app with comparison, it will always have to be added.

For a `raster` source the minimum amount of properties needed are a `mapLabel` and a `source`
```
mapLabel: () => 'Foo vs Bar',
source: {
  type: 'raster',
  tiles: [
    'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/GPW_Population_Density_2020/default/2020-04-14T00:00:00Z/GoogleMapsCompatible_Level7/{z}/{y}/{x}.png'
  ]
}
```

**Comment by olafveerman** [comment]
Thanks @danielfdsilva, this is great. 

## Adding compare to AQ
The latest commit adds the compare visuals to the AQ story. I found it to be relatively straightforward, but am running into an issue with the [VIIRS visual](https://github.com/NASA-IMPACT/covid-dashboard/pull/462/commits/972a70aa1deae94d292362cef623d8ac5d49c9b9#diff-168625ebacf8073befc4fcfebfaf66228270f6a0dff66b0604ce77dfd942e3ffR192). Enabling it, results in:

`Error: Layer definition not found for story layer with id [nightlights-viirs]`

## Testing rest of site
Did a test of the site, and didn't notice any regression. I did find a bug with the compare functionality in the latest release, but will ticket that separately.

**Comment by danielfdsilva** [comment]
@olafveerman pushed a fix for the `nightlights-viirs` layers. Problem was using `spotlightId` instead of `spotlight`. (maybe we should change it to the id version?)

Additionally the date must be set with `compareDate` instead of a simple `date`.

**Comment by danielfdsilva** [comment]
The last commit adds support for small multiples with maps.
All the maps are synced between them, so moving/zooming on one, applies to all the others.
:warning: Only raster maps are supported at the moment.

On large screens the maps are displayed in a grid depending on the number of maps.
If the map count fits neatly in a grid with 3 columns that is used. (Eg: 3, 6, 9...)

Screen Shot 2020-11-24 at 22 31 21

Else if the map count fits neatly in a grid with 2 columns that is used. (Eg: 2, 4, 8...)

Screen Shot 2020-11-24 at 22 31 34

Else a grid of 3 is used with any empty column left empty.

On mobile, all the maps are displayed side-by-side and there's a navigation to allow the user to switch between them.

Screen Shot 2020-11-24 at 22 32 14

To enable this use the following code:
```
visual: {
  type: 'multi-map',
  data: {
    bbox: [115.84, 39.62, 116.85, 40.22], // The bbox is not mandatory. If not provided [0, 0] with a zoom of 2 is used.
    maps: [
      {
        id: 'mb-1', // The id is mandatory and must be unique in all maps.
        label: 'Map 1', // The label to be displayed over the map
        source: {
          type: 'raster',
          tiles: [
            // raster tile url
          ]
        }
      }
      // ... more maps to display.
    ]
  }
}
```

cc @olafveerman

**Comment by olafveerman** [comment]
:heart: this. Did a quick test with the NO2 baseline product, and the `multi-map` worked very well.

ezgif com-gif-maker (1)


## Regression
There's a regression with existing map layers that have the compare enabled. Eg. `http://localhost:9000/stories/air-quality/cities-experiencing-clearer-air/beijing`

```
Uncaught TypeError: Cannot read property 'mbMap' of null
    at StoriesSingle.updateItemVisuals (index.js:339)
    at StoriesSingle.componentDidUpdate (index.js:292)
    at commitLifeCycles (react-dom.development.js:19835)
    at commitLayoutEffects (react-dom.development.js:22803)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at commitRootImpl (react-dom.development.js:22541)
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
```

**Comment by danielfdsilva** [comment]
@olafveerman Regression fixed, and a treat. :)

**Comment by olafveerman** [comment]
Damn Daniel, I love treats.

LGTM, let's merge into the stories branch.

**Pull request merged**
